# Generated by Django 3.2.6 on 2021-08-27 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='likes',
            field=models.ManyToManyField(default=1, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
