# Generated by Django 3.2.6 on 2021-08-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_eventlist_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='likes',
        ),
    ]
