# Generated by Django 3.2.6 on 2021-08-27 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_eventlist_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 27, 8, 24, 5, 84868, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='event_date',
            field=models.DateField(),
        ),
    ]
